title: Mohammed Shibin K
description: Cyber Security Portfolio.
baseurl: "/mohdshibin"
url: "https://shibzzz.github.io"
author:
  name: "Your Name"
  email: "your.email@example.com"
social:
  github: "https://github.com/yourusername"
  linkedin: "https://linkedin.com/in/yourprofile"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - README.md

